channels:
  - defaults
  - conda-forge

dependencies:
  - python>=3.6.7
  - rasterio>=1.0.28
  - ipykernel
  - xarray

  - pip:
    - matplotlib
    - tifffile
    - deepdiff
    - gitpython
    - netcdf4